//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitorTray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 30")]
        public global::System.Drawing.Color applicationBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["applicationBackgroundColor"]));
            }
            set {
                this["applicationBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color applicationForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["applicationForegroundColor"]));
            }
            set {
                this["applicationForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool applicationSound {
            get {
                return ((bool)(this["applicationSound"]));
            }
            set {
                this["applicationSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool applicationStartWithWindows {
            get {
                return ((bool)(this["applicationStartWithWindows"]));
            }
            set {
                this["applicationStartWithWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point detailsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["detailsFormLocation"]));
            }
            set {
                this["detailsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size detailsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["detailsFormSize"]));
            }
            set {
                this["detailsFormSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65, 140, 240")]
        public global::System.Drawing.Color detailsFormReceivedChartColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["detailsFormReceivedChartColor"]));
            }
            set
            {
                this["detailsFormReceivedChartColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 180, 65")]
        public global::System.Drawing.Color detailsFormSentChartColor
        {
            get
            {
                return ((global::System.Drawing.Color)(this["detailsFormSentChartColor"]));
            }
            set
            {
                this["detailsFormSentChartColor"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point settingsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["settingsFormLocation"]));
            }
            set {
                this["settingsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size settingsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["settingsFormSize"]));
            }
            set {
                this["settingsFormSize"] = value;
            }
        }
    }
}
